name = "mycontainer"

#entrypoint = """
#echo "Hello, I started at $(date)" > /mount/point/proof
#"""

[image]
distro = "alpine"
release = "3.19"
arch = "amd64"
#dir = /path/to/rootfs

[limits]
cpuset_cpus = "1,2"

#[[copy]]
#host = "."
#container = "/"
#follow_link = true

[[copy]]
host = "../../README.md"
container = "./README.md"
#archive = true

[[shared]]
host = "/home/davidjosearaujo/Downloads"
container = "mount/point"

[[run]]
cmd = "touch bye"